package bit.project.server;

import bit.project.server.util.security.SystemModule;

public enum UsecaseList{
    @SystemModule("User") SHOW_ALL_USERS(1),
    @SystemModule("User") SHOW_USER_DETAILS(2),
    @SystemModule("User") ADD_USER(3),
    @SystemModule("User") UPDATE_USER(4),
    @SystemModule("User") DELETE_USER(5),
    @SystemModule("User") RESET_USER_PASSWORDS(6),
    @SystemModule("Role") SHOW_ALL_ROLES(7),
    @SystemModule("Role") SHOW_ROLE_DETAILS(8),
    @SystemModule("Role") ADD_ROLE(9),
    @SystemModule("Role") UPDATE_ROLE(10),
    @SystemModule("Role") DELETE_ROLE(11),
    @SystemModule("Customer") SHOW_ALL_CUSTOMERS(12),
    @SystemModule("Customer") SHOW_CUSTOMER_DETAILS(13),
    @SystemModule("Customer") ADD_CUSTOMER(14),
    @SystemModule("Customer") UPDATE_CUSTOMER(15),
    @SystemModule("Customer") DELETE_CUSTOMER(16),
    @SystemModule("Customerpayment") SHOW_ALL_CUSTOMERPAYMENTS(17),
    @SystemModule("Customerpayment") SHOW_CUSTOMERPAYMENT_DETAILS(18),
    @SystemModule("Customerpayment") ADD_CUSTOMERPAYMENT(19),
    @SystemModule("Customerpayment") UPDATE_CUSTOMERPAYMENT(20),
    @SystemModule("Customerpayment") DELETE_CUSTOMERPAYMENT(21),
    @SystemModule("Customerreturn") SHOW_ALL_CUSTOMERRETURNS(22),
    @SystemModule("Customerreturn") SHOW_CUSTOMERRETURN_DETAILS(23),
    @SystemModule("Customerreturn") ADD_CUSTOMERRETURN(24),
    @SystemModule("Customerreturn") UPDATE_CUSTOMERRETURN(25),
    @SystemModule("Customerreturn") DELETE_CUSTOMERRETURN(26),
    @SystemModule("Disposal") SHOW_ALL_DISPOSALS(27),
    @SystemModule("Disposal") SHOW_DISPOSAL_DETAILS(28),
    @SystemModule("Disposal") ADD_DISPOSAL(29),
    @SystemModule("Disposal") UPDATE_DISPOSAL(30),
    @SystemModule("Disposal") DELETE_DISPOSAL(31),
    @SystemModule("Employee") SHOW_ALL_EMPLOYEES(32),
    @SystemModule("Employee") SHOW_EMPLOYEE_DETAILS(33),
    @SystemModule("Employee") ADD_EMPLOYEE(34),
    @SystemModule("Employee") UPDATE_EMPLOYEE(35),
    @SystemModule("Employee") DELETE_EMPLOYEE(36),
    @SystemModule("Item") SHOW_ALL_ITEMS(37),
    @SystemModule("Item") SHOW_ITEM_DETAILS(38),
    @SystemModule("Item") ADD_ITEM(39),
    @SystemModule("Item") UPDATE_ITEM(40),
    @SystemModule("Item") DELETE_ITEM(41),
    @SystemModule("Purchase") SHOW_ALL_PURCHASES(42),
    @SystemModule("Purchase") SHOW_PURCHASE_DETAILS(43),
    @SystemModule("Purchase") ADD_PURCHASE(44),
    @SystemModule("Purchase") UPDATE_PURCHASE(45),
    @SystemModule("Purchase") DELETE_PURCHASE(46),
    @SystemModule("Purchaseorder") SHOW_ALL_PURCHASEORDERS(47),
    @SystemModule("Purchaseorder") SHOW_PURCHASEORDER_DETAILS(48),
    @SystemModule("Purchaseorder") ADD_PURCHASEORDER(49),
    @SystemModule("Purchaseorder") UPDATE_PURCHASEORDER(50),
    @SystemModule("Purchaseorder") DELETE_PURCHASEORDER(51),
    @SystemModule("Sale") SHOW_ALL_SALES(52),
    @SystemModule("Sale") SHOW_SALE_DETAILS(53),
    @SystemModule("Sale") ADD_SALE(54),
    @SystemModule("Sale") UPDATE_SALE(55),
    @SystemModule("Sale") DELETE_SALE(56),
    @SystemModule("Supplier") SHOW_ALL_SUPPLIERS(57),
    @SystemModule("Supplier") SHOW_SUPPLIER_DETAILS(58),
    @SystemModule("Supplier") ADD_SUPPLIER(59),
    @SystemModule("Supplier") UPDATE_SUPPLIER(60),
    @SystemModule("Supplier") DELETE_SUPPLIER(61),
    @SystemModule("Supplierpayment") SHOW_ALL_SUPPLIERPAYMENTS(62),
    @SystemModule("Supplierpayment") SHOW_SUPPLIERPAYMENT_DETAILS(63),
    @SystemModule("Supplierpayment") ADD_SUPPLIERPAYMENT(64),
    @SystemModule("Supplierpayment") UPDATE_SUPPLIERPAYMENT(65),
    @SystemModule("Supplierpayment") DELETE_SUPPLIERPAYMENT(66),
    @SystemModule("Supplierreturn") SHOW_ALL_SUPPLIERRETURNS(67),
    @SystemModule("Supplierreturn") SHOW_SUPPLIERRETURN_DETAILS(68),
    @SystemModule("Supplierreturn") ADD_SUPPLIERRETURN(69),
    @SystemModule("Supplierreturn") UPDATE_SUPPLIERRETURN(70),
    @SystemModule("Supplierreturn") DELETE_SUPPLIERRETURN(71),
    @SystemModule("Vehicle") SHOW_ALL_VEHICLES  (72),
    @SystemModule("Vehicle") SHOW_VEHICLE_DETAILS(73),
    @SystemModule("Vehicle") ADD_VEHICLE(74),
    @SystemModule("Vehicle") UPDATE_VEHICLE(75),
    @SystemModule("Vehicle") DELETE_VEHICLE(76);

    public final int value;

    UsecaseList(int value){
        this.value = value;
    }

}
